#forgithub
source:         ./
destination:    /vhmis/WebRoot/tuyensinh
host:           0.0.0.0
port:           9001
baseurl:        
url:            http://localhost
excerpt_separator: <!--more-->
encoding:       UTF-8
exclude:        [node_modules, Gruntfile.js, README.md, package.json, nbproject]
